# Site settings
title: Overwatch @ Western Washington University
email: wwuoverwatch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Western Washington University's Official Overwatch eSports Organization
baseurl:
url: /
twitter_username: wwuoverwatch
# github_username:  jekyll

# Build settings
markdown: kramdown
